import json
import os
import re
from datetime import date, datetime, timedelta
from pathlib import Path

import warnings

from jarvis.git_sync import sync


def get_config():
    from jarvis.config import REPO_PATH, DAILY_LOGS_PATH, GEMINI_API_KEY, INDEX_PATH
    return REPO_PATH, DAILY_LOGS_PATH, GEMINI_API_KEY, INDEX_PATH

try:
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", FutureWarning)
        import google.generativeai as genai
except Exception:
    genai = None


MODEL_NAME = "gemini-2.0-flash"


REPO_PATH, DAILY_LOGS_PATH, GEMINI_API_KEY, INDEX_PATH = get_config()
if genai and GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)


def _coerce_date(target_date=None):
    if target_date is None:
        return date.today()
    if isinstance(target_date, datetime):
        return target_date.date()
    return target_date


def get_log_path(target_date=None):
    REPO_PATH, DAILY_LOGS_PATH, _, _ = get_config()
    log_date = _coerce_date(target_date)
    log_dir = DAILY_LOGS_PATH / str(log_date.year) / f"{log_date:%m}"
    log_dir.mkdir(parents=True, exist_ok=True)
    return log_dir / f"{log_date.isoformat()}.md"


def _template(date_iso):
    return f"""# {date_iso}

## Summary
<!-- AI generated at end of day -->

## Captured Notes
<!-- Notes appended here automatically throughout the day -->

## Technologies Used
<!-- Detected from notes automatically -->

## Domains Covered
<!-- Auto-detected from notes -->

## LeetCode / DSA
<!-- DSA notes captured today -->

## Bugs Fixed
<!-- Bug notes captured today -->

## Key Learnings
<!-- Most important insights from today -->

## Tomorrow
<!-- What to focus on next -->

---
*Auto-generated by Jarvis | {date_iso}*
"""


def ensure_log_exists(target_date=None):
    REPO_PATH, DAILY_LOGS_PATH, _, _ = get_config()
    log_date = _coerce_date(target_date)
    log_path = get_log_path(log_date)
    log_path.parent.mkdir(parents=True, exist_ok=True)
    if not log_path.exists():
        log_path.write_text(_template(log_date.isoformat()), encoding="utf-8")
    else:
        _upgrade_existing_log(log_path, log_date)
    return log_path


def _load_lines(log_path):
    return log_path.read_text(encoding="utf-8").splitlines(keepends=True)


def _write_lines(log_path, lines):
    log_path.write_text("".join(lines), encoding="utf-8")


def _find_section_index(lines, header):
    for index, line in enumerate(lines):
        if line.strip() == header:
            return index
    raise ValueError(f"Section not found: {header}")


def _section_insert_position(lines, header):
    index = _find_section_index(lines, header)
    if index + 1 < len(lines) and lines[index + 1].strip().startswith("<!--"):
        return index + 2
    return index + 1


def _insert_line_in_section(log_path, header, entry_line):
    lines = _load_lines(log_path)
    position = _section_insert_position(lines, header)
    lines.insert(position, entry_line if entry_line.endswith("\n") else f"{entry_line}\n")
    _write_lines(log_path, lines)


def _extract_section_block(content, start_header, end_header=None):
    if start_header not in content:
        return ""
    start = content.index(start_header) + len(start_header)
    remainder = content[start:]
    if end_header and end_header in remainder:
        block = remainder.split(end_header, 1)[0]
    else:
        block = remainder
    return block.strip()


def _upgrade_existing_log(log_path, log_date):
    content = log_path.read_text(encoding="utf-8")
    required_headers = [
        "## Summary",
        "## Captured Notes",
        "## Technologies Used",
        "## Domains Covered",
        "## LeetCode / DSA",
        "## Bugs Fixed",
        "## Key Learnings",
        "## Tomorrow",
    ]
    if all(header in content for header in required_headers):
        return

    captured_block = _extract_section_block(content, "## Captured Notes")
    summary_block = _extract_section_block(content, "## Summary", "## Captured Notes")

    upgraded = _template(log_date.isoformat())
    if summary_block and "AI generated at end of day" not in summary_block:
        upgraded = upgraded.replace("<!-- AI generated at end of day -->", summary_block.strip())

    log_path.write_text(upgraded, encoding="utf-8")

    if captured_block:
        for line in captured_block.splitlines():
            stripped = line.strip()
            if stripped and not stripped.startswith("<!--"):
                _insert_line_in_section(log_path, "## Captured Notes", stripped)


def _replace_section_block(content, start_header, end_header, replacement_body):
    if start_header not in content or end_header not in content:
        return content
    start = content.index(start_header) + len(start_header)
    remainder = content[start:]
    if end_header in remainder:
        before = content[:start]
        after = remainder.split(end_header, 1)[1]
        replacement = f"\n{replacement_body}\n\n{end_header}"
        return before + replacement + after
    return content


def _append_unique_items(log_path, header, items):
    lines = _load_lines(log_path)
    header_index = _find_section_index(lines, header)
    end_index = len(lines)
    for index in range(header_index + 1, len(lines)):
        if lines[index].startswith("## "):
            end_index = index
            break

    existing = set()
    for line in lines[header_index + 1 : end_index]:
        stripped = line.strip()
        if stripped.startswith("-"):
            existing.add(stripped.lstrip("- ").strip().lower())

    insert_position = _section_insert_position(lines, header)
    for item in items:
        clean_item = str(item).strip()
        if not clean_item:
            continue
        if clean_item.lower() in existing:
            continue
        lines.insert(insert_position, f"- {clean_item}\n")
        insert_position += 1
        existing.add(clean_item.lower())

    _write_lines(log_path, lines)


def _section_bullet_texts(content, header):
    if header not in content:
        return []
    start = content.index(header) + len(header)
    remainder = content[start:]
    next_header_match = re.search(r"^##\s+.+$", remainder, flags=re.MULTILINE)
    block = remainder[: next_header_match.start()] if next_header_match else remainder
    items = []
    for line in block.splitlines():
        stripped = line.strip()
        if stripped.startswith("-"):
            items.append(stripped.lstrip("- ").strip())
    return items


def _clean_captured_note(text):
    cleaned = re.sub(r"^`\d{2}:\d{2}`\s*", "", text).strip()
    cleaned = re.sub(r"^\[[^\]]+\]\s*", "", cleaned).strip()
    cleaned = re.sub(r"\s+—\s*\[[^\]]+\]\([^\)]+\)$", "", cleaned).strip()
    return cleaned


def _fallback_daily_summary(log_content):
    captured = [_clean_captured_note(item) for item in _section_bullet_texts(log_content, "## Captured Notes")]
    techs = _section_bullet_texts(log_content, "## Technologies Used")
    domains = _section_bullet_texts(log_content, "## Domains Covered")
    dsa_items = _section_bullet_texts(log_content, "## LeetCode / DSA")
    bug_items = _section_bullet_texts(log_content, "## Bugs Fixed")

    note_samples = [item for item in captured if item][:3]
    tech_samples = [item for item in techs if item][:3]
    domain_samples = [item for item in domains if item][:3]

    pieces = []
    if note_samples:
        pieces.append(f"You worked on {', '.join(note_samples[:-1])} and {note_samples[-1]}.") if len(note_samples) > 1 else pieces.append(f"You worked on {note_samples[0]}.")
    if tech_samples:
        pieces.append(f"You also revisited {', '.join(tech_samples[:-1])} and {tech_samples[-1]} across the day.") if len(tech_samples) > 1 else pieces.append(f"You also revisited {tech_samples[0]} across the day.")
    if domain_samples:
        pieces.append(f"The log shows a mix of {', '.join(domain_samples[:-1])} and {domain_samples[-1]} work.") if len(domain_samples) > 1 else pieces.append(f"The log shows a strong focus on {domain_samples[0]} work.")
    if dsa_items or bug_items:
        pieces.append("You balanced DSA practice with debugging, which suggests you were moving between problem-solving and implementation details.")
    pieces.append("Your notes show consistent capture of practical engineering lessons and recurring technologies.")
    return " ".join(pieces)


def _fallback_weekly_summary(combined_logs):
    captured = [_clean_captured_note(item) for item in _section_bullet_texts(combined_logs, "## Captured Notes")]
    techs = _section_bullet_texts(combined_logs, "## Technologies Used")
    domains = _section_bullet_texts(combined_logs, "## Domains Covered")
    dsa_items = _section_bullet_texts(combined_logs, "## LeetCode / DSA")
    bug_items = _section_bullet_texts(combined_logs, "## Bugs Fixed")

    focus = ", ".join(dict.fromkeys([item for item in techs[:5] if item])) or "practical engineering topics"
    dsa_progress = f"You captured {len(dsa_items)} DSA notes and kept practicing patterns like {', '.join(dict.fromkeys(dsa_items[:3])) if dsa_items else 'sliding windows and pointer movement'}."
    bug_progress = f"You documented {len(bug_items)} bugs and kept a debugging trail across the week."
    consistency = f"Your logs show {len(set(captured))} unique captured notes and a steady habit of writing things down as you learned them."
    next_focus = f"Next week, keep building on {focus} and continue pairing implementation notes with debugging follow-ups."
    return (
        "## This Week's Focus\n"
        f"You focused on {focus}.\n\n"
        "## DSA Progress\n"
        f"{dsa_progress}\n\n"
        "## Bugs & Debugging\n"
        f"{bug_progress}\n\n"
        "## Learning Consistency\n"
        f"{consistency}\n\n"
        "## Next Week: Focus On\n"
        f"{next_focus}"
    )


def append_to_log(text, source, source_url, note_type, classification=None, target_date=None):
    log_path = ensure_log_exists(target_date)
    time_value = datetime.now().strftime("%H:%M")
    url_part = f" — [{source_url}]({source_url})" if source_url else ""
    captured_entry = f"- `{time_value}` [{source}] {text[:80]}{url_part}"

    _insert_line_in_section(log_path, "## Captured Notes", captured_entry)

    if note_type == "dsa":
        _insert_line_in_section(log_path, "## LeetCode / DSA", f"- `{time_value}` {text[:80]}")

    if note_type == "bug":
        _insert_line_in_section(log_path, "## Bugs Fixed", f"- `{time_value}` {text[:80]}")

    return log_path


def update_technologies(classification, target_date=None):
    if not classification:
        return ensure_log_exists(target_date)

    log_path = ensure_log_exists(target_date)
    subdomain = str(classification.get("subdomain", "")).strip()
    tags = classification.get("tags", []) or []
    domain = str(classification.get("domain", "")).strip()

    tech_items = []
    if subdomain:
        tech_items.append(subdomain)
    tech_items.extend(tags)

    _append_unique_items(log_path, "## Technologies Used", tech_items)
    _append_unique_items(log_path, "## Domains Covered", [domain] if domain else [])
    return log_path


def _load_index_notes_for_date(target_date):
    _, _, _, INDEX_PATH = get_config()
    if not INDEX_PATH.exists():
        return []
    try:
        data = json.loads(INDEX_PATH.read_text(encoding="utf-8"))
    except Exception:
        return []
    notes = data.get("notes", []) if isinstance(data, dict) else []
    target_iso = _coerce_date(target_date).isoformat()
    return [note for note in notes if note.get("date") == target_iso]


def _summary_bullets_for_date(target_date):
    notes = _load_index_notes_for_date(target_date)
    concepts = sum(1 for note in notes if note.get("type") == "concept")
    dsa = sum(1 for note in notes if note.get("type") == "dsa")
    bugs = sum(1 for note in notes if note.get("type") == "bug")
    snippets = sum(1 for note in notes if note.get("type") == "snippet")
    return (
        f"- {concepts} concept notes captured\n"
        f"- {dsa} DSA problems\n"
        f"- {bugs} bugs documented\n"
        f"- {snippets} snippets saved"
    )


def _generate_summary_text(log_content):
    _, _, GEMINI_API_KEY, _ = get_config()
    prompt = f"""
You are Jarvis, an AI engineering journal assistant.
Below is a developer's raw daily log containing their captured notes.
Generate a concise narrative summary (4-6 sentences) of what they worked on,
what they learned, and what patterns you notice in their learning today.
Be specific, mention actual technologies and topics from the log.
Write in second person: "You worked on..."

Daily log:
{log_content}

Return only the summary text. No headers. No markdown. Just the paragraph.
"""

    try:
        from jarvis.ai import complete

        summary_text = complete(prompt, max_tokens=600, temperature=0.4) or ""
        summary_text = re.sub(r"\s+", " ", summary_text).strip()
        return summary_text or _fallback_daily_summary(log_content)
    except Exception:
        return _fallback_daily_summary(log_content)


def finalize_log(target_date=None):
    log_date = _coerce_date(target_date)
    log_path = get_log_path(log_date)
    if not log_path.exists():
        return f"No log found for {log_date.isoformat()}"

    log_content = log_path.read_text(encoding="utf-8")
    summary_text = _generate_summary_text(log_content)
    log_content = _replace_section_block(log_content, "## Summary", "## Captured Notes", summary_text)
    key_learnings = _summary_bullets_for_date(log_date)
    if "<!-- Most important insights from today -->" in log_content:
        log_content = log_content.replace("<!-- Most important insights from today -->", key_learnings)
    else:
        log_content = _replace_section_block(log_content, "## Key Learnings", "## Tomorrow", key_learnings)
    log_path.write_text(log_content, encoding="utf-8")
    
    # Sync to GitHub
    commit_msg = f"log: finalize daily log {log_date.isoformat()}"
    sync_result = sync(commit_msg)
    if sync_result.get("synced"):
        print(f"✓ Log synced to GitHub [{sync_result['commit_sha']}]")
    elif sync_result.get("committed") and sync_result.get("push_error"):
        print(f"⚠ Log committed but push failed: {sync_result['push_error']}")
    
    return f"✓ Log finalized for {log_date.isoformat()}"


def get_week_logs(target_date=None):
    end_date = _coerce_date(target_date)
    week_logs = []
    for offset in range(6, -1, -1):
        current_date = end_date - timedelta(days=offset)
        log_path = get_log_path(current_date)
        exists = log_path.exists()
        content = log_path.read_text(encoding="utf-8") if exists else ""
        week_logs.append({"date": current_date.isoformat(), "content": content, "exists": exists})
    return week_logs


def generate_weekly_summary(target_date=None):
    REPO_PATH, _, GEMINI_API_KEY, _ = get_config()
    end_date = _coerce_date(target_date)
    week_logs = get_week_logs(end_date)
    combined_logs = "\n\n".join(log["content"] for log in week_logs if log["exists"])

    prompt = f"""
You are Jarvis, an AI engineering journal assistant.
Below are 7 days of a developer's engineering logs.
Generate a weekly summary covering:
1. Main topics and technologies studied this week
2. DSA problems solved and patterns practiced
3. Bugs encountered and fixed
4. Overall learning progress and consistency
5. Recommendation for what to focus on next week

Be specific and reference actual topics from the logs.
Write in second person. Use markdown with these exact headers:
## This Week's Focus
## DSA Progress
## Bugs & Debugging
## Learning Consistency
## Next Week: Focus On

Logs:
{combined_logs}
"""

    try:
        from jarvis.ai import complete

        summary_text = complete(prompt, max_tokens=1500, temperature=0.4) or ""
    except Exception:
        summary_text = ""

    if not summary_text.strip():
        summary_text = _fallback_weekly_summary(combined_logs)

    week_number = end_date.isocalendar().week
    summary_path = REPO_PATH / "weekly-summaries" / f"{end_date.year}-W{week_number:02d}.md"
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    summary_path.write_text(summary_text, encoding="utf-8")
    
    # Sync to GitHub
    commit_msg = f"log: weekly summary {end_date.year}-W{week_number:02d}"
    sync_result = sync(commit_msg)
    if sync_result.get("synced"):
        print(f"✓ Weekly summary synced to GitHub [{sync_result['commit_sha']}]")
    elif sync_result.get("committed") and sync_result.get("push_error"):
        print(f"⚠ Weekly summary committed but push failed: {sync_result['push_error']}")
    
    return summary_path
