"""
Documentation generator (`jar export`).

Turns a scattered set of notes into ONE clean, shareable Markdown document —
a domain handbook, a pattern cheatsheet, an interview prep pack.

This is the "documentation agent" side of Jarvis: capture is per-thought, but
what you actually want to hand someone (or re-read before an interview) is a
single coherent document. Selection reuses the existing search/index layers, so
you can export by domain, tag, type, or free-text query.
"""

import re
from datetime import date

from jarvis.config import REPO_PATH
from jarvis.index_store import load_index

_FRONTMATTER_RE = re.compile(r"^---\n.*?\n---\n", re.DOTALL)
_PLACEHOLDER_RE = re.compile(r"<!--.*?-->", re.DOTALL)
_FOOTER_RE = re.compile(r"^\*Captured:.*$", re.MULTILINE)


def _clean_body(raw, strip_empty_sections=True):
    """Strip frontmatter, placeholders and the Jarvis footer from a note."""
    body = _FRONTMATTER_RE.sub("", raw, count=1)
    body = _PLACEHOLDER_RE.sub("", body)
    body = _FOOTER_RE.sub("", body)
    body = re.sub(r"\n-{3,}\s*$", "", body.strip())

    if strip_empty_sections:
        # Drop "## Heading" blocks that have no content under them.
        blocks = re.split(r"\n(?=##\s)", body)
        kept = []
        for block in blocks:
            lines = block.strip().splitlines()
            if lines and lines[0].startswith("##"):
                content = "\n".join(lines[1:]).strip()
                if not content:
                    continue
            kept.append(block.strip())
        body = "\n\n".join(kept)

    return body.strip()


def select_notes(domain=None, tag=None, note_type=None, query=None, limit=None):
    """Pick notes by any combination of filters. De-duplicated by file."""
    if query:
        from jarvis.retrieval import search_notes

        hits = search_notes(query, limit=limit or 50)
        wanted = {(h["folder_path"], h["filename"]) for h in hits}
    else:
        wanted = None

    selected = []
    seen = set()
    for note in load_index().get("notes", []):
        key = (note.get("folder_path", ""), note.get("filename", ""))
        if key in seen:
            continue
        if wanted is not None and key not in wanted:
            continue
        if domain and note.get("domain") != domain:
            continue
        if note_type and note.get("type") != note_type:
            continue
        if tag and tag not in (note.get("tags") or []):
            continue
        path = REPO_PATH / key[0] / key[1]
        if not path.exists():
            continue
        seen.add(key)
        selected.append({**note, "path": path})

    selected.sort(key=lambda n: (n.get("domain", ""), n.get("subdomain", ""),
                                 n.get("title", "")))
    if limit:
        selected = selected[:limit]
    return selected


def _slug(text):
    return re.sub(r"[^a-z0-9]+", "-", (text or "").lower()).strip("-")


def build_document(notes, title, include_toc=True, include_sources=True):
    """Render selected notes into one Markdown document."""
    if not notes:
        return f"# {title}\n\n_No notes matched._\n"

    parts = [f"# {title}", ""]
    parts.append(f"_Generated by Jarvis on {date.today().isoformat()} "
                 f"from {len(notes)} note(s)._")
    parts.append("")

    if include_toc:
        parts.append("## Contents")
        current_domain = None
        for note in notes:
            dom = note.get("domain", "other")
            if dom != current_domain:
                parts.append(f"- **{dom}**")
                current_domain = dom
            parts.append(f"  - [{note.get('title', 'Untitled')}](#{_slug(note.get('title'))})")
        parts.append("")
        parts.append("---")
        parts.append("")

    current_domain = None
    for note in notes:
        dom = note.get("domain", "other")
        if dom != current_domain:
            parts.append(f"## {dom}")
            parts.append("")
            current_domain = dom

        parts.append(f"### {note.get('title', 'Untitled')}")
        tags = note.get("tags") or []
        meta_bits = []
        if note.get("subdomain"):
            meta_bits.append(f"`{note['subdomain']}`")
        if tags:
            meta_bits.append(" ".join(f"`{t}`" for t in tags[:5]))
        if meta_bits:
            parts.append(" ".join(meta_bits))
        parts.append("")

        try:
            raw = note["path"].read_text(encoding="utf-8")
        except Exception:
            raw = ""
        body = _clean_body(raw)
        # The note's own H1 duplicates the ### heading we just wrote.
        body = re.sub(r"^#\s+.*$", "", body, count=1, flags=re.MULTILINE).strip()
        # Demote remaining headings so they nest under our ###.
        body = re.sub(r"^##\s", "#### ", body, flags=re.MULTILINE)
        parts.append(body if body else "_(no content yet)_")

        if include_sources and note.get("source_url"):
            parts.append("")
            parts.append(f"Source: <{note['source_url']}>")
        parts.append("")
        parts.append("---")
        parts.append("")

    return "\n".join(parts).rstrip() + "\n"


def export(domain=None, tag=None, note_type=None, query=None, limit=None,
           title=None, output=None, include_toc=True):
    """Select + render + write. Returns {"path", "count", "title"}."""
    notes = select_notes(domain=domain, tag=tag, note_type=note_type,
                         query=query, limit=limit)

    if not title:
        descriptor = domain or tag or note_type or query or "Knowledge Base"
        title = f"{str(descriptor).replace('-', ' ').title()} — Handbook"

    document = build_document(notes, title, include_toc=include_toc)

    if output:
        from pathlib import Path

        out_path = Path(output)
    else:
        out_path = REPO_PATH / "00-meta" / "exports" / f"{_slug(title)}.md"

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(document, encoding="utf-8")

    return {"path": str(out_path), "count": len(notes), "title": title}
